### ISSUE TITLE
How do I specify load path for files?  

### ISSUE THREAD

**Issue by chuyler** [altgifted/babel-plugin-transform-scss#19]
Previously this would have been solved by something like this...
`{ loader: 'sass-loader',
  options: {
    includePaths: ['node_modules']
  }
}`

I have some paths that worked previously but I cannot figure out how to point this module to look in the right folders.

`@import '@salesforce-ux/design-system/design-tokens/dist/ui-force.default';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/DateInput/index.scss 1:9  root stylesheet
    at Object.wrapException (/project/node_modules/sass/sass.dart.js:1247:17)
    at _EvaluateVisitor1._evaluate0$_loadStylesheet$4$baseUrl$forImport (/project/node_modules/sass/sass.dart.js:81032:19)
    at _EvaluateVisitor1._evaluate0$_loadStylesheet$3$forImport (/project/node_modules/sass/sass.dart.js:81065:19)
    at _EvaluateVisitor__visitDynamicImport_closure1.call$0 (/project/node_modules/sass/sass.dart.js:82838:21)
    at _EvaluateVisitor1._evaluate0$_withStackFrame$1$3 (/project/node_modules/sass/sass.dart.js:82046:25)
    at _EvaluateVisitor1._evaluate0$_withStackFrame$3 (/project/node_modules/sass/sass.dart.js:82052:19)
    at _EvaluateVisitor1._evaluate0$_visitDynamicImport$1 (/project/node_modules/sass/sass.dart.js:80994:19)
    at _EvaluateVisitor1.visitImportRule$1 (/project/node_modules/sass/sass.dart.js:80968:17)
    at ImportRule0.accept$1$1 (/project/node_modules/sass/sass.dart.js:86043:22)
    at ImportRule0.accept$1 (/project/node_modules/sass/sass.dart.js:86046:19) {
formatted: "Error: Can't find stylesheet to import.\n"`

**Comment by altgifted** [comment]
you can pass options in plugin

```
{
  "presets": [],
  "plugins": [
    ["babel-plugin-transform-scss", {"include": ["node_modules"]}]
  ]
}
```
